FifteenPuzzle/Lesson_ASP.NET_MVC/Models/MainModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lesson_ASP.NET_MVC.Models
{
    public class MainModel
    {
        public string str1 { get; set; }
        public string str2 { get; set; }
        public string concat {
            get { return str1 + str2; }
        }
    }
}

FifteenPuzzle/Lesson_ASP.NET_MVC/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lesson_ASP.NET_MVC.Models;

namespace Lesson_ASP.NET_MVC.Controllers
{
    public class MainController : Controller
    {
        // GET: Main
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(MainModel model)
        {
            ViewBag.Result = model.concat;
            return View();
        }
    }
}

FifteenPuzzle/Lesson_ASP.NET_MVC/Views/Main/Index.cshtml
@using System.Security.Policy
@model Lesson_ASP.NET_MVC.Models.MainModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Index", "Main"))
        {
            @Html.TextBoxFor(x => x.str1)
            @Html.TextBoxFor(x=>x.str2)
            <input type="submit" value="Check"/>
            <p>Result = @ViewBag.Result</p>
        } 
    </div>
</body>
</html>