FifteenPuzzle/FifteenPuzzle.Client/Models/PuzzleGameModel.cs
using FifteenPuzzle.BLL;

namespace FifteenPuzzle.Client.Models
{
    public class PuzzleGameModel
    {
        private PuzzleGame _instanceGame;

        public PuzzleGameModel()
        {
            _instanceGame = new PuzzleGame();
        }

        public PuzzleGame GetInstance {
            get { return _instanceGame; }
        }
    }
}

FifteenPuzzle/FifteenPuzzle.Client/Controllers/PuzzleGameController.cs
using System.Web.Mvc;
using FifteenPuzzle.Client.Models;

namespace FifteenPuzzle.Client.Controllers
{
    public class PuzzleGameController : Controller
    {
        [HttpGet]
        public ActionResult Index(string value)
        {
            var instanse = Session["Game"] as PuzzleGameModel;

            if (instanse == null)
            {
                instanse = new PuzzleGameModel();
                Session["Game"] = instanse;

                return View(instanse);
            }

            if (!instanse.GetInstance.Ready) return View(instanse);


            var currentPuzzle = instanse.GetInstance.GetByValue(value);
            if (currentPuzzle != null) instanse.GetInstance.Go(currentPuzzle);
            instanse.GetInstance.Verify();

            Session["Game"] = instanse;

            return View(instanse);
        }

        [HttpGet]
        public ActionResult NewGame(bool reset = false)
        {
            var instanse = Session["Game"] as PuzzleGameModel;

            if (!reset) return View("Index", instanse);
            if (instanse != null)
                instanse.GetInstance.Shuffle();

            return View("Index", instanse);
        }

    }
}

FifteenPuzzle/FifteenPuzzle.Client/Views/PuzzleGame/Index.cshtml
@model FifteenPuzzle.Client.Models.PuzzleGameModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/PuzzleStyle.css" rel="stylesheet" />
    <title>Index</title>
</head>
<body>
    <div class="col-sm-3">
        <div hidden="@Model.GetInstance.Ready">
            <div class="panel panel-success">
                <div class="panel-heading">Exelent!!! You WIN!</div>
                <div class="panel-body">
                    @Html.ActionLink("Play again", "NewGame", "PuzzleGame", new { reset = true }, new { @class = "hrefClassName", @id = "hrefId" })
                </div>
            </div>
        </div>

        <div class="panel panel-info">
            <div class="panel-heading">PuzzleGame</div>
            <div class="panel-body">
                <div class="form-group">
                    <table class="table">
                        <thead></thead>
                        <tbody>
                            @for (var i = 0; i < 4; i++)
                            {
                            <tr>
                                @for (var j = 0; j < 4; j++)
                                    {
                                    <td class="btn btn-primary" onclick="location.href='@Url.Action("Index", "PuzzleGame", new{ Value=@Model.GetInstance.GetPuzzlesField[i, j].PuzzleValue })'">
                                        @Model.GetInstance.GetPuzzlesField[i, j].PuzzleValue
                                    </td>
                                    }
                            </tr>
                            }
                        </tbody>

                        <tfoot>
                            <tr><td colspan="4"><div><b>Steps: </b>@Model.GetInstance.Steps</div></td></tr>
                            <tr><td colspan="4">@Html.ActionLink("New Game", "NewGame", "PuzzleGame", new { reset = true }, new { @class = "hrefClassName", @id = "hrefId" })</td></tr>
                        </tfoot>
                    </table>
                </div>

            </div>
        </div>

    </div>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>